#!/bin/bash 
#SBATCH -J inferencer
#SBATCH -o /share/ju/matt/street-flooding/notebooks/cambrian/logs/%j.out 
#SBATCH -e /share/ju/matt/street-flooding/notebooks/cambrian/logs/%j.err 
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu 
#SBATCH -N 1
#SBATCH -n 8
#SBATCH --get-user-env 
#SBATCH --mem=64gb
#SBATCH -t 400:00:00 
#SBATCH --gpus=1
#SBATCH --partition=pierson

pwd
source /home/mwf62/.bashrc
 
source activate /share/ju/conda_virtualenvs/cambrian

cd /share/ju/matt/street-flooding/notebooks/cambrian

python inferencer_noltbx.py