#!/bin/bash 
#SBATCH -J baselines
#SBATCH -o /share/ju/matt/bayflood/.slurm_jobs/baselines/%j.out 
#SBATCH -e /share/ju/matt/bayflood/.slurm_jobs/baselines/%j.err
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu 
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --get-user-env 
#SBATCH --mem=128gb
#SBATCH -t 400:00:00 
#SBATCH --partition=pierson


pwd
source /home/mwf62/.bashrc
 
source activate /share/ju/conda_virtualenvs/stan

cd /share/ju/matt/bayflood

# Run baseline comparisons using the unified pipeline
python pipeline.py \
    --geometry-type ct \
    --external-covariates \
    --skip-data-generation \
    --compare-to-baselines \
    --prefix FINAL_COMMS_BASELINES