#!/bin/bash 
#SBATCH -J fit
#SBATCH -o /share/ju/matt/bayflood/.slurm_jobs/fit/%j.out 
#SBATCH -e /share/ju/matt/bayflood/.slurm_jobs/fit/%j.err
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu 
#SBATCH -N 1
#SBATCH -n 8
#SBATCH --get-user-env 
#SBATCH --mem=400gb
#SBATCH -t 400:00:00 
#SBATCH --partition=pierson


pwd
source /home/mwf62/.bashrc
 

cd /share/ju/matt/bayflood
source .venv/bin/activate
python pipeline.py --geometry-type $2 --prefix $1 --external-covariates --downsample-frac $3 --downsample-all-images
