#!/bin/bash 
#SBATCH -J fit
#SBATCH -o /share/ju/matt/bayflood/.slurm_jobs/fit/%j.out 
#SBATCH -e /share/ju/matt/bayflood/.slurm_jobs/fit/%j.err
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu
#SBATCH -N 1
#SBATCH -n 8
#SBATCH --get-user-env 
#SBATCH --mem=64gb
#SBATCH -t 400:00:00 
#SBATCH --partition=pierson


pwd
source $HOME/.bashrc
 

cd $REPO_ROOT
source .venv/bin/activate


# args: icar_prior_setting, annotations_have_locations, use_simulated_data
python icar_model.py icar --annotations_have_locations --external_covariates --prefix $1