#!/bin/bash 
#SBATCH -J traffic
#SBATCH -o /share/ju/journalism/claustrophobic-streets/log/traffic/%j.out 
#SBATCH -e /share/ju/journalism/claustrophobic-streets/log/traffic/%j.err
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu 
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --get-user-env 
#SBATCH --mem=192gb
#SBATCH -t 400:00:00 
#SBATCH --partition=ju

pwd
source /home/mwf62/.bashrc
 
source activate /share/ju/conda_virtualenvs/urbanekg

cd /share/ju/journalism/claustrophobic-streets/segmentize-first-analysis

python traffic.py