#!/bin/bash 
#SBATCH -J janus_inferencer
#SBATCH -o /share/ju/matt/street-flooding/notebooks/janus/logs/worker/%j.out 
#SBATCH -e /share/ju/matt/street-flooding/notebooks/janus/logs/worker/%j.err 
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu 
#SBATCH -N 1
#SBATCH -n 4
#SBATCH --get-user-env 
#SBATCH --mem=48gb
#SBATCH -t 400:00:00 
#SBATCH --gpus=1
#SBATCH --partition=pierson

pwd
source /home/mwf62/.bashrc
 
source activate /share/ju/conda_virtualenvs/janus

cd /share/ju/matt/street-flooding/notebooks/janus

echo "Starting inference"

python inferencer.py $1
